### ISSUE TITLE
I have to modify code in Goban so that it can be built using preact-cli

### ISSUE THREAD

**Issue by restingisimportant** [SabakiHQ/Shudan#13]
![image](https://user-images.githubusercontent.com/2382992/57972175-1802da80-79c1-11e9-8d80-e921bb097d34.png)

I have to modify code in Goban right this so it can be built in preact-cli without any problems, am i missing something here ?

**Comment by yishn** [comment]
You’re probably using an old version of preact. Use a version that supports getDerivedStateFromProps, such as 8.4.2.

**Comment by restingisimportant** [comment]
![image](https://user-images.githubusercontent.com/2382992/57979142-7c667e00-7a43-11e9-80a8-698a9e2db44d.png)
Upgraded to preact 8.4.2 but still does not work

**Comment by yishn** [comment]
Can you build and run the demo?

**Comment by restingisimportant** [comment]
> Can you build and run the demo?

Yes, I can.

**Comment by restingisimportant** [comment]
I create a new preact project using create-preact-app with material template here and use Goban in shudan. it does not work.

Here is the git repository.
https://github.com/restingisimportant/preact-cli-shudan

Also i don't know why the stone does not appeared now, i must be missing something

**Comment by yishn** [comment]
In the git repository, you’re using an old version of preact. Are you sure you tried updating preact to 8.4.2?

**Comment by restingisimportant** [comment]
> In the git repository, you’re using an old version of preact. Are you sure you tried updating preact to 8.4.2?

Hi, Sorry i forgot to update it for this one, now i updated it already. but problems still persist.

![image](https://user-images.githubusercontent.com/2382992/58097437-951c9280-7c01-11e9-97cb-7201d64200a5.png)

Also, the board does not show up completely

**Comment by yishn** [comment]
I suspect it's a transpilation issue of `[...Array(n)]`. I've changed it to `Array(n).fill(0)` to circumvent it. Can you try updating Shudan to v1.3.12 and see if it's working for you?

**Comment by restingisimportant** [comment]
![image](https://user-images.githubusercontent.com/2382992/58117229-4c2c0480-7c28-11e9-873b-4e5e5195f9ad.png)

Board does show correctly now.

![image](https://user-images.githubusercontent.com/2382992/58117172-2d2d7280-7c28-11e9-90ed-51ac1781e378.png)

However, build command still not success.

You can test by this repository
https://github.com/restingisimportant/preact-cli-shudan

**Comment by yishn** [comment]
It seems like preact-cli doesn't support `getDerivedStateFromProps` during prerender yet. Either don't use prerender (by running `preact build --no-prerender` like it suggested) or use the non-stable next version of preact-cli.

**Comment by restingisimportant** [comment]
> It seems like preact-cli doesn't support `getDerivedStateFromProps` during prerender yet. Either don't use prerender (by running `preact build --no-prerender` like it suggested) or use the non-stable next version of preact-cli.

I got issue about preact build --no-prerender before. it does work now.
Thank you very much.
