### ISSUE TITLE
Possible issue with old mobile browser.

### ISSUE THREAD

**Issue by sarawut-positwinyu** [SabakiHQ/Shudan#14]
![image](https://user-images.githubusercontent.com/2382992/58100073-25110b00-7c07-11e9-8318-f8fce8625eda.png)

My friend use xiaomi and found this issue, it does work will on desktop and many mobile phones though. Is there any suggestion of why this bug might happened ?

**Comment by yishn** [comment]
I'm not planning to support old mobile browsers. But if someone has a fix for it, they can feel free to submit a pull request.
