### ISSUE TITLE
Board graphic bug

### ISSUE THREAD

**Issue by AntonProskurin90** [SabakiHQ/Shudan#3]
Hello! 
Sometimes, when i resize window, i can see bold lines, like this:
![image](https://user-images.githubusercontent.com/45637302/52577501-4d80b080-2e33-11e9-9953-6cbd3fbdb7b8.png)

In web vesion too.

**Comment by yishn** [comment]
After some experimentation, it seems that we can achieve uniform looking lines at all zoom levels using `<rect>` and coordinates in pixels.
